services:
  database:
    image: 'postgres:latest'
    ports:
      - '5433:5433'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=root'
    volumes:
      - '~/volumes/choubeyshubham/postgres:/var/lib/postgresql/data'
